-- V1__init_schema.sql
-- Schema inicial de auth-service (estado previo al commit 2c47105).
-- Hibernate con ddl-auto=create-drop generaba este mismo schema a partir
-- de las entities; cualquier desviacion aqui provocara un fallo de
-- ddl-auto=validate al arrancar.
--
-- Tipos:
--   - IDs: BIGINT/INT GENERATED BY DEFAULT AS IDENTITY (JPA estandar,
--     Hibernate 6 + PostgreSQL 10+ + H2 en modo PostgreSQL).
--   - Timestamps: TIMESTAMP(6) WITH TIME ZONE (microsecond precision,
--     que es lo que Hibernate 6 genera para java.time.Instant).
--   - Booleans: BOOLEAN (Hibernate no traduce el field initializer de
--     Java a SQL DEFAULT; el default se aplica en el lado Java).

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_login_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- Tabla join ManyToMany entre User y Role (definida en User.java con
-- @JoinTable(name = "user_roles", ...)).
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    replaced_by_token_id BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Indice declarado en RefreshToken con @Index(name = "idx_refresh_expires_at", ...).
CREATE INDEX idx_refresh_expires_at ON refresh_tokens(expires_at);
