-- V3__add_email_verification_tokens.sql
-- Crea la tabla de tokens de verificacion de email para el flujo
-- de confirmacion de cuenta tras el registro.
--
-- Mismo patron que password_reset_tokens: hash SHA-256 (VARCHAR 255),
-- FK a users con ON DELETE CASCADE, columna version para optimistic
-- locking de Hibernate (@Version).

CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
