-- V4__add_audit_events.sql
-- Crea la tabla de auditoria (append-only) para registrar eventos
-- de seguridad y negocio: logins, cambios de password, verificaciones
-- de email, refreshes de token, etc.
--
-- Sin FK con ON DELETE CASCADE: si un usuario se elimina, sus eventos
-- de auditoria deben conservarse (integridad historica). El campo
-- user_id queda como NULL si el usuario referenciado desaparece.

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL,
    user_id BIGINT,
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    details VARCHAR(1000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_audit_events_type ON audit_events(event_type);
CREATE INDEX idx_audit_events_user ON audit_events(user_id);
CREATE INDEX idx_audit_events_created ON audit_events(created_at);
